### ISSUE TITLE
Aura's still displaying after load/reload when the setting is switched off.

### ISSUE THREAD

**Issue by CadoCat** [Hydra-Mods/HydraUI#115]
Raising from the discord. The fix is adding the following to the Auras.LUA file in the function Auras:Load() section:

```
        if Settings["auras-show"] then
		for i = 1, 2 do
			Auras.Headers[i]:Show()
		end
	else
		for i = 1, 2 do
			Auras.Headers[i]:Hide()
		end
	end
```

**Comment by Hydra-Mods** [comment]
After double checking the code and testing it myself, my only conclusion is that the player isn't using a current version where the auras disable properly. Adding the code you suggested is actually redundant since Auras:Load() evaluates Settings["auras-show"] first and then bails from any aura creation

**Comment by CadoCat** [comment]
I tested again and it's definitely not functioning correctly. I'm on 2.132 and could replicate the issue.
![image](https://github.com/Hydra-Mods/HydraUI/assets/113401819/cfd50974-9ddb-4b0f-a4c3-f38e39c846fc)

I couldn't find anywhere in the Auras:Load() a check for theSettings["auras-show"].

**Comment by Hydra-Mods** [comment]
My mistake here, I misunderstood and thought we were talking about the enable setting! This was easily adjusted
